=== eduardomello/gitabs/user-story-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "User Story",
    "description": "A User Story",
    "type": "object",
    "properties": {
		  	"title": {
		  		"description": "A significant title",
		  		"type": "string"
		  	},
		  	"content": {
		  		"description": "As an [actor] I want [action] so that [achievement]",
		  		"type": "string"
		  	},
		  	"status": {
		  		"enum": ["todo","doing","done"]
		  	},
		  	"effort": {
		  		"description": "total effort time for getting user story done",
		  		"type": "integer",
		  		"minimum": 0,
		  		"maximum": 8
		  	},
		  	"spent": {
		  		"description": "time already spent on user story",
		  		"type": "integer",
		  		"minimum": 0,
		  		"maximum": 8
		  	},
		  	"acceptance_criteria":
		  	{
		  		"type": "array",
		  		"items": {
		  			"type": "object",
		  			"properties": {
		  				"criteria" : { "description": "some criteria", "type": "string"},
		  				"status" : { "enum":["not tested", "working"]}
		  			}
		  		},
		  		"minItems": 1,
		  		"uniqueItems": true
		  		
		  	}    
    },
    "required": ["title", "content", "status", "effort", "acceptance_criteria"]
    
}

=== eduardomello/gitabs/create-blank-repository.json
{
		"title": "Create blank repository",
		"content": "As a project manager I want to create a blank repository so that i can start modeling the meta-data on it",
		"status": "todo",
		"effort": 0,
		"acceptance_criteria":
		[
			{ "criteria": "create directory", "status": "not tested" },
			{ "criteria": "initiate git repository on created directory", "status": "not tested" }
		]
			
}

=== eduardomello/gitabs/create-meta-branch.json
{
		"title": "Create meta-branch",
		"content": "As a project manager I want create a meta-branch on some repository so i can start storing meta-data on it",
		"status": "doing",
		"effort": 5,
		"acceptance_criteria":
		[
			{ "criteria": "Be able to run 'git tabs meta-branch'", "status": "not tested" },
			{ "criteria": "'git tabs meta-branch' need a json-schema file as parameter", "status": "not tested" },
			{ "criteria": "json-schema file must be valid", "status": "not tested" },
			{ "criteria": "New branch named after json-schema file must be added", "status": "not tested" },
			{ "criteria": "New branch must have a single file: the json-schema file", "status": "not tested" },
			{ "criteria": "Commit the new file to the branch", "status": "not tested" }
		]
			
	}

=== eduardomello/gitabs/add-meta-data.json
{
		"title": "Add meta-data",
		"content": "As a general user I want to add meta-data on a branch so i can register different activities of a project",
		"status": "todo",
		"effort": 5,
		"acceptance_criteria":
		[
			{ "criteria": "Be able to run 'git tabs meta-data -a'", "status": "not tested" },
			{ "criteria": "'git tabs meta-data -a' need a meta-branch parameter", "status": "not tested" },
			{ "criteria": "shell must query user for each field on json-schema", "status": "not tested" },
			{ "criteria": "Valid json file must be added to meta-branch", "status": "not tested" },
			{ "criteria": "Commit the new file to the branch", "status": "not tested" }
		]
			
	}

=== eduardomello/gitabs/edit-meta-data-schema.json
{
		"title": "Edit meta-data schema",
		"content": "As a repository manager I want to edit meta-data schema on a meta-branch",
		"status": "todo",
		"effort": 5,
		"acceptance_criteria":
		[
			{ "criteria": "Be able to run 'git tabs meta-branch'", "status": "not tested" },
			{ "criteria": "'git tabs meta-branch' need a json-schema file as parameter", "status": "not tested" },
			{ "criteria": "json-schema file must be valid", "status": "not tested" },
			{ "criteria": "Branch named after json-schema file must be rewritten", "status": "not tested" },
			{ "criteria": "Commit the new file to the branch", "status": "not tested" }			
		]
			
	}
